---
# task file to configure bash completion for gcloud
- name: gcloud | Archive | Debian | Ensure bash completion is installed
  apt: name=bash-completion
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  when: ansible_os_family == "Debian"

- name: gcloud | Archive | RedHat | Ensure bash completion is installed
  yum:
    name:
      - bash-completion
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  when: ansible_os_family == "RedHat"

- name: gcloud | Archive | Ensure bash_completion.d directory exists
  file:
    path: /etc/bash_completion.d
    owner: root
    group: root
    state: directory

- name: gcloud | Archive | Link binaries to /usr/bin (like package install)
  file:
    src: "{{ gcloud_library_path }}/completion.bash.inc"
    dest: /etc/bash_completion.d/gcloud
    state: link
