---
dependencies: []

galaxy_info:
  role_name: pip
  author: geerlingguy
  description: Pip (Python package manager) for Linux.
  issue_tracker_url: https://github.com/geerlingguy/ansible-role-pip/issues
  company: "Midwestern Mac, LLC"
  license: "MIT"
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - system
    - server
    - packaging
    - python
    - pip
    - tools
