---
# tasks file for stackdriver_logging

- name: Stackdriver Logging | OS Based Installation
  include_tasks: "{{ ansible_os_family|lower }}.yml"

- name: Stackdriver Logging | Install the Stackdriver defaults file
  template:
    src: default/google-fluentd
    dest: /etc/default/google-fluentd
  when: stackdriver_http_proxy is defined or
        stackdriver_https_proxy is defined

- name: Stackdriver Logging | Install the logging files
  template:
    src: source.conf
    dest: /etc/google-fluentd/config.d/{{ item.name }}.conf
  loop: "{{ stackdriver_log_files }}"
  when: stackdriver_log_files is defined
  notify: Stackdriver Logging | Restart Stackdriver Agent
