---
- name: Stackdriver Monitoring | Debian | Add the Stackdriver repository
  apt_repository:
    repo: "deb {{ stackdriver_mon_apt_repo_url }} {{ stackdriver_mon_apt_repo_name }} main"
    filename: google-cloud-monitoring
    state: present

- name: Stackdriver Monitoring | Debian | Ensure Stackdriver's GPG key is available.
  apt_key:
    url: "{{ stackdriver_mon_apt_repo_url }}/doc/apt-key.gpg"
    state: present

- name: Stackdriver Monitoring | Debian | Install the Stackdriver agent
  apt:
    name: "{{ stackdriver_mon_package_name }}"
    state: present
    update_cache: yes
  notify: Stackdriver Monitoring | Restart Stackdriver Agent
