---
galaxy_info:
  author: ericsysmin
  role_name: stackdriver_monitoring
  description: Ansible role to install Stackdriver monitoring agent
  license: Apache-2.0
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 6
        - 7
        - 8
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
  galaxy_tags: []
dependencies: []
