---
- name: "Ansible login with password prompt"
  hosts: node1
  remote_user: newuser
  gather_facts: false
  #vars_prompt:
  #  - name: ansible_password
  #    prompt: What is your password?
  #    private: yes
  tasks:
    - name: Test connection 
      ping: