---
# tasks file for deploy-web-server
- name: Delete content & directory
  ansible.builtin.file:
    state: absent
    path: /var/www/html

- name: Create directory
  ansible.builtin.file:
    state: directory
    path: /var/www/html
    mode: '0755'

- name: Install httpd and firewalld
  ansible.builtin.yum:
    name: 
      - httpd
      - firewalld
      - git
    state: latest

- name: Enable and Run Firewalld
  ansible.builtin.service: 
    name: firewalld
    enabled: true
    state: started

- name: firewalld permitt httpd service
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: yes

- name: httpd enabled and running
  ansible.builtin.service:
    name: httpd
    enabled: true
    state: started
    
- name: Git checkout
  ansible.builtin.git:
    repo: 'https://github.com/everimus/one-page-website'
    dest: /var/www/html
    version: gh-pages

- name: Set Hostname on Site
  ansible.builtin.replace:
    path: /var/www/html/index.html
    regexp: 'Installed using Ansible'
    replace: "Installed using Ansible. {{ inventory_hostname }}"