---
- name: Install Chrony Package
  hosts: node1
  become: true
  tasks:
    - name: Ensure chrony package is installed
      ansible.builtin.dnf:
        name: chrony
        state: latest

    - name: Copy chrony configuration to node
      ansible.builtin.copy:
        src: chrony.conf.sample
        dest: /etc/chrony.conf
        mode: 644
        owner: root
        group: root
    
    - name: Enable and start chrony Service
      ansible.builtin.systemd:
        name: chronyd
        state: started
        enabled: yes
        masked: no