- name: "Ensure sudo is installed"
  dnf:
    name: sudo
    state: present
  when: "'01.01' not in baseline_exclusions"

- name: "Ensure sudo log file exists"
  lineinfile:
    path: /etc/sudoers
    regexp: '^Defaults\s*logfile="{{ sudo_log }}"'
    line: 'Defaults logfile="{{ sudo_log }}"'
    insertafter: "^# Defaults specification"
    validate: /usr/sbin/visudo -cf %s
  when: "'01.02' not in baseline_exclusions"