# part-01.yml

- name: "Ensure sudo is installed"
  dnf:
    name: sudo
    state: present

- name: "Ensure sudo log file exists"
  lineinfile:
    path: /etc/sudoers
    regexp: '^Defaults\s*logfile="{{ sudo_log }}"'
    line: 'Defaults logfile="{{ sudo_log }}"'
    insertafter: "^# Defaults specification"
    validate: /usr/sbin/visudo -cf %s