- name: "Ensure message of the day is configured properly"
  copy:
    src: "{{ motd_file }}"
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644
  when: "'02.01' not in baseline_exclusions"
  
- name: "Ensure local login warning banner is configured properly"
  copy:
    src: "{{ issue_file }}"
    dest: /etc/issue
    owner: root
    group: root
    mode: 0644
  when: "'02.02' not in baseline_exclusions"